Ej1 Escribe un programa Pandas para conectarte a la base de datos datafundamentals y carga los pagos como un dataframe

EJ1 Version 2

In [1]:
import psycopg2

def create_pg_connection():
    conn = None
    try: 
        conn = psycopg2.connect(database='data fundamentals', user='data fundamentals_owner', password='t6v1eQALByal', host='ep-autumn-violet-a5sfis6z.us-east-2.aws.neon.tech', port=5432)
        print('Database conn succesful')
    except Exception as err:
        print(f"Error: '{err}'")

    return conn

In [2]:
#Generamos la conexión a la base de datos

import pandas as pd

conn_pg = create_pg_connection()

Database conn succesful

In [3]:

#Leer la base de datos

df = pd.read_sql_query("SELECT * FROM payments ", conn_pg)
conn_pg.close()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259 entries, 0 to 258
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customernumber  259 non-null    int64
 1   checknumber     259 non-null    object
 2   paymentdate     259 non-null    object
 3   amount          259 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 8.2+ KB

/tmp/ipykernel_3497/1297803866.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM payments ", conn_pg)

In [4]:
df.head()

   customernumber checknumber paymentdate    amount
0             103    HQ336336  2004-10-19   6066.78
1             103    JM555205  2003-06-05  14571.44
2             103    OM314933  2004-12-18   1676.14
3             112    BO864823  2004-12-17  14191.12
4             112     HQ55022  2003-06-06  32641.98

In [5]:
df.tail()

     customernumber checknumber paymentdate    amount
254             495    BH167026  2003-12-26  59265.14
255             495    FN155234  2004-05-14   6276.60
256             496    EU531600  2005-05-25  30253.75
257             496    MB342426  2003-07-16  32077.44
258             496     MN89921  2004-12-31  52166.00

In [6]:
df.describe()

       customernumber         amount
count      259.000000     259.000000
mean       270.779923   32419.803707
std        120.336164   20633.076867
min        103.000000    1128.200000
25%        161.000000   17195.910000
50%        250.000000   32077.440000
75%        359.500000   44989.560000
max        496.000000  120166.580000

EJ 2 Escribe un programa Pandas para conectarte a la base de datos datafundamentals y guardar el df de pagos en una tabla nueva. Luego muestra las tablas en la bbdd y comprueba que existe la nueva tabla.
Tip: Usar sqlalchemy (https://www.sqlalchemy.org/)

# !pip install sqlalchemy

from sqlalchemy import create_engine
engine = create_engine('db_url')
df.sql('table_name',engine)

In [7]:
#!pip install sqlalchemy

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    'postgresql://datafundamentasl_owner:yPDtEpT5R6mI@ep-super-meadow-a2w5lasv.eu-central-1.aws.neon.tech/datafundamentasl?sslmode=require')

#df[:10].to_sql('pagos2',engine,index=False)

ValueError: Table 'pagos2' already exists.

EJ 3. Escribe un programa en pandas para seleccionar filas donde el valor de la columna "amount" sea mayor de 400

In [9]:
df[df['amount']>400]

     customernumber checknumber paymentdate    amount
0               103    HQ336336  2004-10-19   6066.78
1               103    JM555205  2003-06-05  14571.44
2               103    OM314933  2004-12-18   1676.14
3               112    BO864823  2004-12-17  14191.12
4               112     HQ55022  2003-06-06  32641.98
..              ...         ...         ...       ...
254             495    BH167026  2003-12-26  59265.14
255             495    FN155234  2004-05-14   6276.60
256             496    EU531600  2005-05-25  30253.75
257             496    MB342426  2003-07-16  32077.44
258             496     MN89921  2004-12-31  52166.00

[259 rows x 4 columns]

EJ. 4 Escribe un programa en pandas para seleccionar solo las columnas 'cheknumber' y 'paymentdate'

In [10]:
df[['amount','paymentdate']]

       amount paymentdate
0     6066.78  2004-10-19
1    14571.44  2003-06-05
2     1676.14  2004-12-18
3    14191.12  2004-12-17
4    32641.98  2003-06-06
..        ...         ...
254  59265.14  2003-12-26
255   6276.60  2004-05-14
256  30253.75  2005-05-25
257  32077.44  2003-07-16
258  52166.00  2004-12-31

[259 rows x 2 columns]

EJ5 Escribe un programa pandas para definir MultiIndex (multi-indice: varios indices para cada fila), para:
    acceder a datos especificos mediante el
    segmentar el dataframe en función de los niveles multiindex

In [11]:
midf = df.set_index(['customernumber','checknumber'])
midf

                           paymentdate    amount
customernumber checknumber
103            HQ336336     2004-10-19   6066.78
               JM555205     2003-06-05  14571.44
               OM314933     2004-12-18   1676.14
112            BO864823     2004-12-17  14191.12
               HQ55022      2003-06-06  32641.98
...                                ...       ...
495            BH167026     2003-12-26  59265.14
               FN155234     2004-05-14   6276.60
496            EU531600     2005-05-25  30253.75
               MB342426     2003-07-16  32077.44
               MN89921      2004-12-31  52166.00

[259 rows x 2 columns]

para el análisis de datos, .loc y .iloc son dos métodos utilizados para acceder a los datos en un DataFrame, pero tienen diferencias clave:

.loc: Se utiliza para acceder a un grupo de filas y columnas por etiquetas o un array booleano. Por ejemplo, df.loc[1:3, 'columna'] selecciona las filas de la 1 a la 3 y la columna llamada 'columna'.

.iloc: Se utiliza para acceder a un grupo de filas y columnas por índices enteros. Por ejemplo, df.iloc[1:3, 0] selecciona las filas de la 1 a la 3 y la primera columna (índice 0).

.loc[]: Es un método de pandas que se utiliza para acceder a un grupo de filas y columnas por etiquetas o una matriz booleana.
(103, 'OM314933'): Es una tupla que especifica la etiqueta de la fila y la etiqueta de la columna que se desea acceder.
En resumen, este código accede al valor en la fila con la etiqueta 103 y la columna con la etiqueta 'OM314933' en el DataFrame midf.

In [12]:
midf.loc[(103,'OM314933')]

paymentdate    2004-12-18
amount            1676.14
Name: (103, OM314933), dtype: object

EJ5. Escribir un programa pandas para seleccionar las primeras tres filas usando iloc

.iloc[]: Es un método de pandas que se utiliza para acceder a filas y columnas por índices enteros (basados en la posición).
:3: Es un índice de corte (slice) que selecciona las filas desde el inicio hasta la tercera fila (no inclusiva).

In [13]:
df.iloc[:3]

   customernumber checknumber paymentdate    amount
0             103    HQ336336  2004-10-19   6066.78
1             103    JM555205  2003-06-05  14571.44
2             103    OM314933  2004-12-18   1676.14

EJ 6 Escribe un programa pandas para usar loc para seleccionar filas aplicando una condicion dada en 2 columnas

In [14]:
mask = (df['amount']>400) & (df['customernumber']>400)
df.loc[mask]

     customernumber checknumber paymentdate    amount
211             406   BJMPR4545  2005-04-23  12190.85
212             406    HJ217687  2004-01-28  49165.16
213             406    NA197101  2004-06-17  25080.96
214             412    GH197075  2004-07-25  35034.57
215             412    PJ434867  2004-04-14  31670.37
216             415     ER54537  2004-09-28  31310.09
217             424    KF480160  2004-12-07  25505.98
218             424    LM271923  2003-04-16  21665.98
219             424    OA595449  2003-10-31  22042.37
220             447    AO757239  2003-09-15   6631.36
221             447    ER615123  2003-06-25  17032.29
222             447    OU516561  2004-12-17  26304.13
223             448    FS299615  2005-04-18  27966.54
224             448    KR822727  2004-09-30  48809.90
225             450    EF485824  2004-06-21  59551.38
226             452    ED473873  2003-11-15  27121.90
227             452    FN640986  2003-11-20  15130.97
228             452    HG635467  2005-05-03   8807.12
229             455    HA777606  2003-12-05  38139.18
230             455    IR662429  2004-05-12  32239.47
231             456    GJ715659  2004-11-13  27550.51
232             456    MO743231  2004-04-30   1679.92
233             458    DD995006  2004-11-15  33145.56
234             458    NA377824  2004-02-06  22162.61
235             458    OO606861  2003-06-13  57131.92
236             462    ED203908  2005-04-15  30293.77
237             462     GC60330  2003-11-08   9977.85
238             462    PE176846  2004-11-27  48355.87
239             471    AB661578  2004-07-28   9415.13
240             471    CO645196  2003-12-10  35505.63
241             473    LL427009  2004-02-17   7612.06
242             473    PC688499  2003-10-27  17746.26
243             475    JP113227  2003-12-09   7678.25
244             475    PB951268  2004-02-13  36070.47
245             484    GK294076  2004-10-26   3474.66
246             484    JH546765  2003-11-29  47513.19
247             486     BL66528  2004-04-14   5899.38
248             486     HS86661  2004-11-23  45994.07
249             486    JB117768  2003-03-20  25833.14
250             487    AH612904  2003-09-28  29997.09
251             487    PT550181  2004-02-29  12573.28
252             489    OC773849  2003-12-04  22275.73
253             489    PO860906  2004-01-31   7310.42
254             495    BH167026  2003-12-26  59265.14
255             495    FN155234  2004-05-14   6276.60
256             496    EU531600  2005-05-25  30253.75
257             496    MB342426  2003-07-16  32077.44
258             496     MN89921  2004-12-31  52166.00

EJ. 7 Escribe un programa pandas que utilice loc para cambiar el valor de amount de las filas que cumplan con una condicion

In [15]:
df.loc[mask,'amount'] = 0
df.loc[mask]

     customernumber checknumber paymentdate  amount
211             406   BJMPR4545  2005-04-23     0.0
212             406    HJ217687  2004-01-28     0.0
213             406    NA197101  2004-06-17     0.0
214             412    GH197075  2004-07-25     0.0
215             412    PJ434867  2004-04-14     0.0
216             415     ER54537  2004-09-28     0.0
217             424    KF480160  2004-12-07     0.0
218             424    LM271923  2003-04-16     0.0
219             424    OA595449  2003-10-31     0.0
220             447    AO757239  2003-09-15     0.0
221             447    ER615123  2003-06-25     0.0
222             447    OU516561  2004-12-17     0.0
223             448    FS299615  2005-04-18     0.0
224             448    KR822727  2004-09-30     0.0
225             450    EF485824  2004-06-21     0.0
226             452    ED473873  2003-11-15     0.0
227             452    FN640986  2003-11-20     0.0
228             452    HG635467  2005-05-03     0.0
229             455    HA777606  2003-12-05     0.0
230             455    IR662429  2004-05-12     0.0
231             456    GJ715659  2004-11-13     0.0
232             456    MO743231  2004-04-30     0.0
233             458    DD995006  2004-11-15     0.0
234             458    NA377824  2004-02-06     0.0
235             458    OO606861  2003-06-13     0.0
236             462    ED203908  2005-04-15     0.0
237             462     GC60330  2003-11-08     0.0
238             462    PE176846  2004-11-27     0.0
239             471    AB661578  2004-07-28     0.0
240             471    CO645196  2003-12-10     0.0
241             473    LL427009  2004-02-17     0.0
242             473    PC688499  2003-10-27     0.0
243             475    JP113227  2003-12-09     0.0
244             475    PB951268  2004-02-13     0.0
245             484    GK294076  2004-10-26     0.0
246             484    JH546765  2003-11-29     0.0
247             486     BL66528  2004-04-14     0.0
248             486     HS86661  2004-11-23     0.0
249             486    JB117768  2003-03-20     0.0
250             487    AH612904  2003-09-28     0.0
251             487    PT550181  2004-02-29     0.0
252             489    OC773849  2003-12-04     0.0
253             489    PO860906  2004-01-31     0.0
254             495    BH167026  2003-12-26     0.0
255             495    FN155234  2004-05-14     0.0
256             496    EU531600  2005-05-25     0.0
257             496    MB342426  2003-07-16     0.0
258             496     MN89921  2004-12-31     0.0

EJ 8 Escribe un programa pandas que utilice .loc para dividir un DataFrame en función de las etiquetas de filas y columnas.

In [21]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]}

index_labels = ['row1', 'row2', 'row3', 'row4']
df = pd.DataFrame(data, index=index_labels)
df

      A  B   C   D
row1  1  5   9  13
row2  2  6  10  14
row3  3  7  11  15
row4  4  8  12  16

In [22]:
# Dividir el DataFrame utilizando .loc
# Seleccionar filas 'row1' y 'row2' y columnas 'A' y 'B'
df_dividido = df.loc[['row1', 'row2'], ['A', 'B']]

# Mostrar el DataFrame dividido
print("\nDataFrame dividido:")
print(df_dividido)

DataFrame dividido:
      A  B
row1  1  5
row2  2  6