In [2]:
import pandas as pd
from tabulate import tabulate

df = pd.read_csv('./titanic.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  Unnamed: 15  0 non-null      float64
dtypes: bool(2), float64(3), int64(4), object(7)
memory usage: 99.3+ KB

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,NaN
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,NaN
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN

1. Escribe un programa Pandas para dividir los pasajeros en cuatro categorías según su edad: (0, 10), (10, 30), (30, 60), (60, 80)

¡Claro! Tanto pd.cut como pd.qcut son funciones de pandas utilizadas para segmentar datos en intervalos, pero tienen diferencias importantes:

Criterio de Segmentación:

pd.cut: Divide los datos en intervalos que tienen el mismo rango (es decir, los intervalos son de igual tamaño). Es útil cuando quieres crear intervalos específicos.
pd.qcut: Divide los datos en intervalos que contienen aproximadamente el mismo número de observaciones (es decir, los intervalos tienen la misma cantidad de datos). Es útil para crear cuartiles, deciles, etc.

Parámetros:

pd.cut: Los parámetros principales son x (los datos a segmentar), bins (el número de intervalos o los límites de los intervalos), y labels (para etiquetar los intervalos).
pd.qcut: Los parámetros principales son x (los datos a segmentar), q (el número de cuartiles, deciles, etc.), y labels (para etiquetar los intervalos).

In [3]:
#SE PUEDE HACER CON CUT O CON GROUPBY
df['cage'] = pd.cut(df['age'], [0,  10,  30, 60, 80])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15,cage
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,NaN,"(10, 30]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN,"(30, 60]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,NaN,"(10, 30]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN,"(30, 60]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN,"(30, 60]"

In [4]:
#ELIMINAMOS LA COLUMNA UNNAMED 15
df.pop('Unnamed: 15')
df.head()
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,cage
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,"(10.0, 30.0]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,"(30.0, 60.0]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,"(10.0, 30.0]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,"(30.0, 60.0]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,"(30.0, 60.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,"(10.0, 30.0]"
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,"(10.0, 30.0]"
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,"(10.0, 30.0]"
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,"(30.0, 60.0]"

2. Escribe un programa Pandas para contar la supervivencia por género, categorías y edad de varias clases. Siendo las categorías de edad: (0, 10), (10, 30), (30, 60), (60, 80)

In [6]:
#EL PIVOT ME DA INFORMACION DE LOS INDIVIDUOS QUE POR CLASE HAN SOBREVIVIDO y GENERA OTRO DATAFRAME
pcdf = df.pivot(columns='class', values='survived')
print(pcdf)
#CONCATENO LOS DOS DATAFRAMES EN UNO CON AXIS 1 ME LO PEGA POR COLUMNAS
ndf = pd.concat([df, pcdf], axis=1)
ndf

class  First  Second  Third
0        NaN     NaN    0.0
1        1.0     NaN    NaN
2        NaN     NaN    1.0
3        1.0     NaN    NaN
4        NaN     NaN    0.0
..       ...     ...    ...
886      NaN     0.0    NaN
887      1.0     NaN    NaN
888      NaN     NaN    0.0
889      1.0     NaN    NaN
890      NaN     NaN    0.0

[891 rows x 3 columns]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,cage,First,Second,Third
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,"(10.0, 30.0]",NaN,NaN,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,"(30.0, 60.0]",1.0,NaN,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,"(10.0, 30.0]",NaN,NaN,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,"(30.0, 60.0]",1.0,NaN,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,"(30.0, 60.0]",NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,"(10.0, 30.0]",NaN,0.0,NaN
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,"(10.0, 30.0]",1.0,NaN,NaN
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN,NaN,0.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,"(10.0, 30.0]",1.0,NaN,NaN
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,"(30.0, 60.0]",NaN,NaN,0.0

AHORA LOS SUPERVIVIENTES LOS QUIERO AGRUPAR POR SEXO Y RANGO DE EDAD
ESTO SE HACE CON UN GROUPBY Y UN AGREGATE, EL 'count' me va sumando los supervivientes

In [9]:
ndf.groupby(['sex', 'cage']).agg({'First': 'count', 'Second': 'count', 'Third': 'count'})

                 First  Second  Third
sex    cage
female (0, 10]       1       8     22
       (10, 30]     34      36     57
       (30, 60]     48      30     22
       (60, 80]      2       0      1
male   (0, 10]       2       9     22
       (10, 30]     24      43    151
       (30, 60]     63      44     76
       (60, 80]     12       3      4

PUEDO RESOLVER EL EJ 2 CON UNA TABLA PIVOTADA Y UNA FUNCIÓN DE AGG AGGFUN

In [13]:
df_tasa = df.pivot_table('survived', index=['sex','cage'], columns='class', aggfunc='count')
df_tasa

class            First  Second  Third
sex    cage
female (0, 10]       1       8     22
       (10, 30]     34      36     57
       (30, 60]     48      30     22
       (60, 80]      2       0      1
male   (0, 10]       2       9     22
       (10, 30]     24      43    151
       (30, 60]     63      44     76
       (60, 80]     12       3      4

¡Buena pregunta! Tanto df.pivot como df.pivot_table son funciones de pandas utilizadas para reorganizar datos, pero tienen algunas diferencias clave:

Uso y Flexibilidad:

df.pivot: Es más simple y directo, pero tiene limitaciones. Solo permite pivotar con una columna de valores y no maneja agregaciones.
df.pivot_table: Es más flexible y potente. Permite realizar agregaciones y trabajar con múltiples columnas de valores.
Agregaciones:

df.pivot: No realiza agregaciones. Si hay duplicados en los índices, lanzará un error.
df.pivot_table: Permite especificar una función de agregación (como mean, sum, etc.) para manejar duplicados.
Parámetros:

df.pivot: Utiliza los parámetros index, columns y values.
df.pivot_table: Además de index, columns y values, incluye parámetros adicionales como aggfunc (función de agregación), fill_value (para rellenar valores faltantes), y margins (para agregar totales).

3. Escribe un programa Pandas para encontrar la tasa de supervivencia por género y edad de las diferentes categorías de varias clases. Agregar la tarifa como una dimensión de columnas y dividir la columna de tarifa en 2 categorías según los valores presentes en las columnas de tarifa

pd.qcut(ndf['fare'], 2, labels=['Low Fare', 'High Fare']):

pd.qcut es una función de pandas que divide los datos en intervalos basados en cuantiles. En este caso, se está dividiendo la columna 'fare' del DataFrame ndf en 2 intervalos.
ndf['fare'] es la columna del DataFrame ndf que contiene las tarifas.
2 indica que queremos dividir los datos en 2 intervalos (cuantiles).
labels=['Low Fare', 'High Fare'] asigna etiquetas a los intervalos resultantes. El primer intervalo (el 50% inferior de las tarifas) se etiquetará como 'Low Fare' y el segundo intervalo (el 50% superior de las tarifas) se etiquetará como 'High Fare'.
Asignación a una nueva columna:

ndf['fare_category'] = ... asigna el resultado de pd.qcut a una nueva columna en el DataFrame ndf llamada 'fare_category'.
Esta nueva columna contendrá las etiquetas 'Low Fare' y 'High Fare' para cada fila, dependiendo de en qué intervalo cae la tarifa correspondiente.

In [9]:
# Dividir la columna 'fare' en 2 categorías
ndf['fare_category'] = pd.qcut(ndf['fare'], 2, labels=['Low Fare', 'High Fare'])
ndf['fare_category']

0       Low Fare
1      High Fare
2       Low Fare
3      High Fare
4       Low Fare
         ...
886     Low Fare
887    High Fare
888    High Fare
889    High Fare
890     Low Fare
Name: fare_category, Length: 891, dtype: category
Categories (2, object): ['Low Fare' < 'High Fare']

Utiliza la función pivot_table de pandas para calcular la tasa de supervivencia promedio (columna 'survived') agrupada por género ('sex'), edad ('cage'), clase ('class') y categoría de tarifa ('fare_category'). La función aggfunc='mean' se usa para calcular el promedio de la columna 'survived' para cada grupo.

In [ ]:

# Calcular la tasa de supervivencia por género, edad, clase y categoría de tarifa
survival_rate = ndf.pivot_table('survived', index=['sex', 'cage', 'class'], columns='fare_category', aggfunc='mean')

# Mostrar el resultado
print(survival_rate)

fare_category           Low Fare  High Fare
sex    cage     class
female (0, 10]  First        NaN   0.000000
                Second       NaN   1.000000
                Third   0.800000   0.411765
       (10, 30] First        NaN   0.970588
                Second  0.933333   0.904762
                Third   0.568182   0.307692
       (30, 60] First        NaN   0.979167
                Second  0.846154   0.941176
                Third   0.142857   0.333333
       (60, 80] First        NaN   1.000000
                Third   1.000000        NaN
male   (0, 10]  First        NaN   1.000000
                Second       NaN   1.000000
                Third   1.000000   0.263158
       (10, 30] First        NaN   0.458333
                Second  0.034483   0.000000
                Third   0.140625   0.130435
       (30, 60] First   0.000000   0.440678
                Second  0.130435   0.047619
                Third   0.109375   0.166667
       (60, 80] First        NaN   0.083333
                Second  0.333333        NaN
                Third   0.000000        NaN

4. Escribe un programa Pandas para calcular la cantidad de mujeres y hombres que había en cada clase de cabina.

ndf.groupby(['pclass', 'sex']): Agrupa el DataFrame ndf por las columnas 'pclass' y 'sex'.
.size(): Calcula el tamaño de cada grupo, es decir, cuenta el número de ocurrencias en cada grupo.
.unstack(fill_value=0): Convierte el resultado de la agrupación en un DataFrame con un índice jerárquico, donde las filas corresponden a 'pclass' y las columnas a 'sex'. Si hay valores faltantes, los rellena con 0.

In [10]:
# Calcular la cantidad de mujeres y hombres en cada clase de cabina
result = ndf.groupby(['pclass', 'sex']).size().unstack(fill_value=0)

print(result)

sex     female  male
pclass
1           94   122
2           76   108
3          144   347

5. Escribe un programa Pandas para separar el género según si viajaron solos o no y obtener la probabilidad de supervivencia.

In [12]:
# Separar por género y si viajaron solos o no
grouped = ndf.groupby(['sex', 'alone'])

# Calcular la probabilidad de supervivencia
survival_prob = grouped['survived'].mean().reset_index()

# Renombrar la columna para mayor claridad
survival_prob.rename(columns={'survived': 'survival_probability'}, inplace=True)

print(survival_prob)

      sex  alone  survival_probability
0  female  False              0.712766
1  female   True              0.785714
2    male  False              0.271084
3    male   True              0.155718

6. Escribe un programa Pandas para crear encontrar la probabilidad de supervivencia por clase, género, embarque en solitario y puerto de embarque.

In [13]:
# Agrupar por 'class', 'sex', 'alone' y 'embarked' y calcular la probabilidad de 'survived'
probabilidad_survived = ndf.groupby(['class', 'sex', 'alone', 'embarked'])['survived'].mean().reset_index()

print(probabilidad_survived)

     class     sex  alone embarked  survived
0    First  female  False        C  1.000000
1    First  female  False        Q  1.000000
2    First  female  False        S  0.941176
3    First  female   True        C  0.944444
4    First  female   True        S  1.000000
5    First    male  False        C  0.473684
6    First    male  False        Q  0.000000
7    First    male  False        S  0.407407
8    First    male   True        C  0.347826
9    First    male   True        S  0.326923
10  Second  female  False        C  1.000000
11  Second  female  False        S  0.923077
12  Second  female   True        C  1.000000
13  Second  female   True        Q  1.000000
14  Second  female   True        S  0.892857
15  Second    male  False        C  0.166667
16  Second    male  False        S  0.300000
17  Second    male   True        C  0.250000
18  Second    male   True        Q  0.000000
19  Second    male   True        S  0.089552
20   Third  female  False        C  0.611111
21   Third  female  False        Q  0.625000
22   Third  female  False        S  0.327586
23   Third  female   True        C  0.800000
24   Third  female   True        Q  0.760000
25   Third  female   True        S  0.466667
26   Third    male  False        C  0.500000
27   Third    male  False        Q  0.100000
28   Third    male  False        S  0.142857
29   Third    male   True        C  0.151515
30   Third    male   True        Q  0.068966
31   Third    male   True        S  0.123762