In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
s = pd.Series({'math':10, 'leng':7, 'art':2})
s

math    10
leng     7
art      2
dtype: int64

In [4]:
print(s[1])

7

/tmp/ipykernel_4951/819424605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [6]:
print(s[:2])

math    10
leng     7
dtype: int64

In [5]:
s = pd.Series([1,2,3,4,5,6])

In [8]:
s.apply(lambda x: x+2+3)

0     6
1     7
2     8
3     9
4    10
5    11
dtype: int64

In [9]:
print(s[s>2])

2    3
3    4
4    5
5    6
dtype: int64

In [10]:
import numpy as np
sx =pd.Series(['a','b',None,'c', np.nan, 'd' ])
sx

0       a
1       b
2    None
3       c
4     NaN
5       d
dtype: object

In [11]:
sy = sx.dropna()
sy

0    a
1    b
3    c
5    d
dtype: object

Pandas series

Ej. 1 Escribe un programa Pandas para cambiar el tipo de datos de una columna o serie dada.
Serie de muestra:
    Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto
Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
tipo: float64

In [3]:
# Crear la serie de datos original
data = pd.Series([100, 200, 'python', 300.12, 400])

print("Serie de datos originales:")
print(data)

# Cambiar el tipo de datos a numérico, forzando errores a NaN
data_numeric = pd.to_numeric(data, errors='coerce')

print("\nCambio a numérico:")
print(data_numeric)
print("tipo:", data_numeric.dtype)

Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64
tipo: float64

Ej. 2 Escribe un programa Pandas para convertir series de listas en una serie.
Ejemplo de salida:
Serie original de listas
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: objeto
Una serie:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: objeto

In [4]:
# Crear la serie original de listas
data = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])

print("Serie original de listas:")
print(data)

# Convertir la serie de listas en una serie plana
flat_series = data.explode().reset_index(drop=True)

print("\nUna serie:")
print(flat_series)
print("dtype:", flat_series.dtype)

Serie original de listas:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

Una serie:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object
dtype: object

Ej 3 Escribe un programa Pandas para agregar algunos datos a una serie existente.
Ejemplo de salida:
Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: objeto

In [5]:
# Crear la serie de datos original
data = pd.Series([100, 200, 'python', 300.12, 400])

print("Serie de datos originales:")
print(data)

# Datos a agregar
new_data = pd.Series([500, 'php'])

# Agregar los nuevos datos a la serie existente
data = data.append(new_data, ignore_index=True)

print("\nSerie de datos después de agregar algunos datos:")
print(data)
print("dtype:", data.dtype)

Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object
dtype: object

/tmp/ipykernel_4558/867442484.py:11: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(new_data, ignore_index=True)

Ej 4 Escribe un programa Pandas para crear otra serie con un subconjunto de datos según un valor y una condición dada.
Ejemplo de salida:
Serie de datos originales:
0      0
1      1
2      2

....

9      9
10    10
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
tipo: int64

In [6]:
# Crear la serie de datos original
data = pd.Series(range(11))

print("Serie de datos originales:")
print(data)
print("tipo:", data.dtype)

# Crear un subconjunto de la serie con valores menores o iguales a 5
subset_data = data[data <= 5]

print("\nSubconjunto de la serie de datos anterior:")
print(subset_data)
print("tipo:", subset_data.dtype)

Serie de datos originales:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
tipo: int64

Ej 5 Escribe un programa Pandas para cambiar el orden del índice de una serie dada.
Ejemplo de salida:
Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
tipo: int64

In [7]:
# Crear la serie de datos original
data = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])

print("Serie de datos originales:")
print(data)
print("tipo:", data.dtype)

# Cambiar el orden del índice
new_index = ['B', 'A', 'C', 'D', 'E']
reordered_data = data.reindex(new_index)

print("\nSerie de datos después de cambiar el orden del índice:")
print(reordered_data)
print("tipo:", reordered_data.dtype)

Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
dtype: int64
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
dtype: int64
tipo: int64

Ej 6 Escribe un programa Pandas para obtener los elementos de una serie dada que no están presentes en otra serie dada.
Ejemplo de salida:  
Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
tipo: int64

In [8]:
# Crear las series originales
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("Serie original:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)

# Obtener los elementos de sr1 que no están presentes en sr2
result = sr1[~sr1.isin(sr2)]

print("\nElementos de sr1 no presentes en sr2:")
print(result)
print("tipo:", result.dtype)

Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
dtype: int64
tipo: int64

Ej 7 Escribe un programa Pandas para calcular el mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie dada.
Ejemplo de salida:
Serie original:
Original Series:
0      3.000938
1     11.370722
2     14.612143

....

17    14.118931
18     8.247458
19     5.526727
tipo: float64

Mínimo, percentil 25, mediana, 75 y máximo de una serie dada:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]

In [7]:
import pandas as pd
import numpy as np

# Crear la serie de datos original
#Crea una serie de pandas llamada data que contiene 20 valores aleatorios generados uniformemente entre 1 y 15.
data = pd.Series(np.random.uniform(1, 15, 20))

print("Serie original:")
print(data)
print("tipo:", data.dtype)

# Calcular el mínimo, percentil 25, mediana, percentil 75 y máximo
statistics = data.quantile([0, 0.25, 0.5, 0.75, 1.0]).values

print("\nMínimo, percentil 25, mediana, 75 y máximo de una serie dada:")
print(statistics)

Serie original:
0      1.266014
1      6.130667
2      5.295866
3      4.432759
4     10.473714
5      6.889480
6      2.423092
7     11.323974
8      7.697898
9     13.692289
10    13.050085
11     2.395516
12    10.111197
13     4.177889
14     5.219655
15     2.714906
16     8.895536
17     7.971114
18    13.788111
19     9.776507
dtype: float64
tipo: float64

Mínimo, percentil 25, mediana, 75 y máximo de una serie dada:
[ 1.26601438  4.36904172  7.29368923 10.20182625 13.78811103]

Ej 8 Escribe un programa Pandas para calcular los conteos de frecuencia de cada valor único de una serie dada.
Ejemplo de salida:
Serie original:
0     1
1     7
2     1
3     6

...


37    0
38    4
39    8
dtype: objeto
Frecuencia de cada valor único de dicha serie.
0    9
2    7
9    6
....
3    2
4    1
5    1
tipo: int64

Este programa crea una serie de datos original con 40 valores aleatorios entre 0 y 9. Luego, utiliza el método value_counts para calcular los conteos de frecuencia de cada valor único en la serie. Finalmente, imprime la serie original, su tipo de datos y los conteos de frecuencia de cada valor único.

In [8]:
# Crear la serie de datos original con valores aleatorios entre 0 y 9
data = pd.Series(np.random.randint(0, 9,10))

print("Serie original:")
print(data)
print("tipo:", data.dtype)

# Calcular los conteos de frecuencia de cada valor único
frequency_counts = data.value_counts()

print("\nFrecuencia de cada valor único de dicha serie:")
print(frequency_counts)
print("tipo:", frequency_counts.dtype)

Serie original:
0    1
1    3
2    6
3    5
4    3
5    5
6    1
7    8
8    7
9    3
dtype: int64
tipo: int64

Frecuencia de cada valor único de dicha serie:
3    3
1    2
5    2
6    1
8    1
7    1
Name: count, dtype: int64
tipo: int64

Ej 9 Escribe un programa Pandas para mostrar el valor más frecuente en una serie dada y reemplazar todo lo demás con el valor 'Otro'.
Ejemplo de salida:
Serie original:
0     3
1     1
2     1
3     3
...
12    2
13    3
14    3
dtype: int64

frecuencias principales: 
2    6
3    5
1    4
tipo: int64

0     Otro
1     Otro
2     Otro
3     Otro
...
11        2
12        2
13    Otro
14    Otro
dtype: objeto

Este programa crea una serie de datos original con 15 valores aleatorios entre 1 y 3. Luego, calcula los conteos de frecuencia de cada valor único utilizando el método value_counts. Obtiene el valor más frecuente con idxmax y reemplaza todos los demás valores con 'Otro' utilizando el método apply. Finalmente, imprime la serie original, las frecuencias principales, y la serie modificada.

In [14]:
# Crear la serie de datos original con valores aleatorios entre 1 y 3
data = pd.Series(np.random.randint(1, 4, 15))

print("Serie original:")
print(data)
print("tipo:", data.dtype)

# Calcular los conteos de frecuencia de cada valor único
frequency_counts = data.value_counts()

print("\nFrecuencias principales:")
print(frequency_counts)
print("tipo:", frequency_counts.dtype)

# Obtener el valor más frecuente
most_frequent_value = frequency_counts.idxmax()

# Reemplazar todos los valores excepto el más frecuente con 'Otro'
data_replaced = data.apply(lambda x: x if x == most_frequent_value else 'Otro')

print("\nSerie después de reemplazar todo lo demás con 'Otro':")
print(data_replaced)
print("tipo:", data_replaced.dtype)

Serie original:
0     3
1     3
2     2
3     2
4     3
5     1
6     2
7     3
8     3
9     3
10    2
11    1
12    2
13    2
14    1
dtype: int64
tipo: int64

Frecuencias principales:
3    6
2    6
1    3
dtype: int64
tipo: int64

Serie después de reemplazar todo lo demás con 'Otro':
0        3
1        3
2     Otro
3     Otro
4        3
5     Otro
6     Otro
7        3
8        3
9        3
10    Otro
11    Otro
12    Otro
13    Otro
14    Otro
dtype: object
tipo: object

Ej 10 Escribe un programa Pandas para obtener las posiciones de los elementos de una serie dada en otra serie dada.
Ejemplo de salida:  
Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
tipo: int64
0     1
1     3
2     5
3     7
4    10
tipo: int64
Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]

In [12]:
import pandas as pd

# Crear las series originales
serie1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
serie2 = pd.Series([1, 3, 5, 7, 10])

# Obtener las posiciones de los elementos de serie2 en serie1
posiciones = [serie1[serie1 == i].index[0] for i in serie2]

# Mostrar las series originales y las posiciones
#for i in serie2: Itera sobre cada valor i en serie2.
#serie1[serie1 == i]: Filtra serie1 para obtener solo los elementos que son iguales a i.
#.index[0]: Obtiene el primer índice del valor filtrado en serie1.
print("Serie original:")
print(serie1)
print("Serie a buscar:")
print(serie2)
print("Posiciones de los elementos de la serie 2 en la serie 1:")
print(posiciones)

Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
Serie a buscar:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]

DATAFRAMES

In [15]:
diccionario = {'nombre': ['María', 'Luis', 'Carmen', 'Antonio'],
       'edad': [18, 22, 20, 21],
       'grado': ['Economía', 'Medicina', 'Arquitectura', 'Economía'],
       'correo': ['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']
       }
       
lista_de_listas = [['María', 18],
         ['Luis', 22],
         ['Carmen', 20]]
                  
lista_de_dicts = [{'Nombre': 'María', 'Edad': 18},
         {'Nombre': 'Luis', 'Edad': 22},
         {'Nombre': 'Carmen'}]

In [17]:
df = pd.DataFrame(diccionario)
df

    nombre  edad         grado             correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [19]:
df = pd.DataFrame(lista_de_dicts)
df

   Nombre  Edad
0   María  18.0
1    Luis  22.0
2  Carmen   NaN

In [21]:
df = pd.DataFrame(lista_de_listas, columns=['Nombre','Edad'])
df

   Nombre  Edad
0   María    18
1    Luis    22
2  Carmen    20

In [ ]:
Dataframes desde archivo

In [14]:
dfcol = pd.read_csv('./colesterol.csv')
print(dfcol)

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [24]:
dffr = pd.read_json('../Numpy/frutas.json')
dffr

       apples  oranges
Luis        3        0
Ana         2        3
Juana       0        7
Pedro       1        2

In [5]:
import sqlite3

In [28]:
con_sqlt = sqlite3.connect("./database.db")
dfdb =pd.read_sql_query("SELECT * FROM movies", con_sqlt)
con_sqlt.close()
dfdb

,title,movieId,genres
0,Toy Story (1995),1,Adventure|Animation|Children|Comedy|Fantasy
1,Jumanji (1995),2,Adventure|Children|Fantasy
2,Grumpier Old Men (1995),3,Comedy|Romance
3,Waiting to Exhale (1995),4,Comedy|Drama|Romance
4,Father of the Bride Part II (1995),5,Comedy
...,...,...,...
9737,Black Butler: Book of the Atlantic (2017),193581,Action|Animation|Comedy|Fantasy
9738,No Game No Life: Zero (2017),193583,Animation|Comedy|Fantasy
9739,Flint (2017),193585,Drama
9740,Bungo Stray Dogs: Dead Apple (2018),193587,Action|Animation
9741,Andrew Dice Clay: Dice Rules (1991),193609,Comedy

In [10]:
#openpyxml

In [30]:

dfxl = pd.read_excel("./FoodMarket.xlsx", sheet_name="Purchases")
dfxl

      Code  Product  Seller  Buyer      Fecha  Quantity
0        1       15      37     90 2020-11-10        25
1        2       46      32     51 2020-09-19        16
2        3       44      27    166 2019-02-19        25
3        4       52      21     68 2020-06-08        40
4        5       20      21    185 2019-01-18        36
...    ...      ...     ...    ...        ...       ...
1496  1497       10      18    199 2020-11-23        34
1497  1498       63      58     38 2020-03-13        35
1498  1499       28       5     81 2020-03-02        31
1499  1500       21       2    194 2021-02-18        35
1500  1501       33       8    120 2020-03-13        12

[1501 rows x 6 columns]

In [3]:
con_sqlt = sqlite3.connect("./database.db")

dfxl.to_sql(name="Purchases",con=con_sqlt)

NameError: name 'sqlite3' is not defined

In [34]:
dfcol.info

NameError: name 'dfcol' is not defined

In [13]:
dfcol.shape

(14, 6)

In [16]:
print(dfcol.columns)
print(dfcol.index)
print(dfcol.axes)
print(dfcol.values)

Index(['nombre', 'edad', 'sexo', 'peso', 'altura', 'colesterol'], dtype='object')
RangeIndex(start=0, stop=14, step=1)
[RangeIndex(start=0, stop=14, step=1), Index(['nombre', 'edad', 'sexo', 'peso', 'altura', 'colesterol'], dtype='object')]
[['José Luis Martínez Izquierdo' 18 'H' 85.0 1.79 182.0]
 ['Rosa Díaz Díaz' 32 'M' 65.0 1.73 232.0]
 ['Javier García Sánchez' 24 'H' nan 1.81 191.0]
 ['Carmen López Pinzón' 35 'M' 65.0 1.7 200.0]
 ['Marisa López Collado' 46 'M' 51.0 1.58 148.0]
 ['Antonio Ruiz Cruz' 68 'H' 66.0 1.74 249.0]
 ['Antonio Fernández Ocaña' 51 'H' 62.0 1.72 276.0]
 ['Pilar Martín González' 22 'M' 60.0 1.66 nan]
 ['Pedro Gálvez Tenorio' 35 'H' 90.0 1.94 241.0]
 ['Santiago Reillo Manzano' 46 'H' 75.0 1.85 280.0]
 ['Macarena Álvarez Luna' 53 'M' 55.0 1.62 262.0]
 ['José María de la Guía Sanz' 58 'H' 78.0 1.87 198.0]
 ['Miguel Angel Cuadrado Gutiérrez' 27 'H' 109.0 1.98 210.0]
 ['Carolina Rubio Moreno' 20 'M' 61.0 1.77 194.0]]

In [17]:
dfcol.head(6)

                         nombre  edad sexo  peso  altura  colesterol
0  José Luis Martínez Izquierdo    18    H  85.0    1.79       182.0
1                Rosa Díaz Díaz    32    M  65.0    1.73       232.0
2         Javier García Sánchez    24    H   NaN    1.81       191.0
3           Carmen López Pinzón    35    M  65.0    1.70       200.0
4          Marisa López Collado    46    M  51.0    1.58       148.0
5             Antonio Ruiz Cruz    68    H  66.0    1.74       249.0

In [18]:
dfcol.describe()

            edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

RENOMBRAR COLUMNAS

In [21]:
dfn = dfcol.rename(columns={'edad':'años'})
dfn

                             nombre  años sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

Para establecer la columna nombre como índice de un DataFrame llamado dfcol, puedes usar el método set_index.

In [22]:
dfcol.set_index("nombre")

                                 edad sexo   peso  altura  colesterol
nombre
José Luis Martínez Izquierdo       18    H   85.0    1.79       182.0
Rosa Díaz Díaz                     32    M   65.0    1.73       232.0
Javier García Sánchez              24    H    NaN    1.81       191.0
Carmen López Pinzón                35    M   65.0    1.70       200.0
Marisa López Collado               46    M   51.0    1.58       148.0
Antonio Ruiz Cruz                  68    H   66.0    1.74       249.0
Antonio Fernández Ocaña            51    H   62.0    1.72       276.0
Pilar Martín González              22    M   60.0    1.66         NaN
Pedro Gálvez Tenorio               35    H   90.0    1.94       241.0
Santiago Reillo Manzano            46    H   75.0    1.85       280.0
Macarena Álvarez Luna              53    M   55.0    1.62       262.0
José María de la Guía Sanz         58    H   78.0    1.87       198.0
Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
Carolina Rubio Moreno              20    M   61.0    1.77       194.0

Para reindexar un DataFrame utilizando un nuevo índice, puedes usar el método reindex.

In [23]:
dfcol.reindex(index=[4,3,1])

                 nombre  edad sexo  peso  altura  colesterol
4  Marisa López Collado    46    M  51.0    1.58       148.0
3   Carmen López Pinzón    35    M  65.0    1.70       200.0
1        Rosa Díaz Díaz    32    M  65.0    1.73       232.0

# EJ 1 Escribe un programa Pandas para conectarte a la base de datos datafundamentals y carga los pagos como un dataframe

In [31]:
import pandas as pd
import psycopg2

PGHOST = 'ep-autumn-violet-a5sfis6z.us-east-2.aws.neon.tech'
PGDATABASE = 'data fundamentals'
PGUSER = 'data fundamentals_owner'
PGPASSWORD = 't6v1eQALByal'

def importar():
    SQL = 'SELECT * FROM payments'
    print('SQL:', SQL)
    
    try:
        conn = psycopg2.connect(
            database=PGDATABASE,
            user=PGUSER,
            password=PGPASSWORD,
            host=PGHOST,
            port=5432
        )
        df = pd.read_sql(SQL, conn)
    except Exception as err:
        print(f"Error: '{err}'")
        df = None
    finally:
        if conn:
            conn.close()
    return df

resultado = importar()
print(resultado)

SQL: SELECT * FROM payments
     customernumber checknumber paymentdate    amount
0               103    HQ336336  2004-10-19   6066.78
1               103    JM555205  2003-06-05  14571.44
2               103    OM314933  2004-12-18   1676.14
3               112    BO864823  2004-12-17  14191.12
4               112     HQ55022  2003-06-06  32641.98
..              ...         ...         ...       ...
254             495    BH167026  2003-12-26  59265.14
255             495    FN155234  2004-05-14   6276.60
256             496    EU531600  2005-05-25  30253.75
257             496    MB342426  2003-07-16  32077.44
258             496     MN89921  2004-12-31  52166.00

[259 rows x 4 columns]

/tmp/ipykernel_3470/892354362.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, conn)

Ej 2 Escribe un programa Pandas para conectarte a la base de datos datafundamentals y guardar el df de pagos en una tabla nueva. Luego muestra las tablas en la bbdd y comprueba que existe la nueva tabla.

In [12]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

# Datos de conexión
PGHOST = 'ep-autumn-violet-a5sfis6z.us-east-2.aws.neon.tech'
PGDATABASE = 'data fundamentals'
PGUSER = 'data fundamentals_owner'
PGPASSWORD = 't6v1eQALByal'

# Función para importar datos de la tabla 'payments'
def importar():
    SQL = 'SELECT * FROM payments'
    print('SQL:', SQL)
    
    try:
        conn = psycopg2.connect(
            database=PGDATABASE,
            user=PGUSER,
            password=PGPASSWORD,
            host=PGHOST,
            port=5432
        )
        df = pd.read_sql(SQL, conn)
    except Exception as err:
        print(f"Error: '{err}'")
        df = None
    finally:
        if conn:
            conn.close()
    return df

# Importar datos de la tabla 'payments'
resultado = importar()
print(resultado)

if resultado is not None:
    # Crear una conexión usando SQLAlchemy
    engine = create_engine(f'postgresql+psycopg2://{PGUSER}:{PGPASSWORD}@{PGHOST}/{PGDATABASE}')

    # Guardar el DataFrame en una nueva tabla llamada 'new_payments'
    resultado.to_sql('new_payments', engine, if_exists='replace', index=False)

    # Conectarse a la base de datos para listar las tablas
    conn = psycopg2.connect(
        database=PGDATABASE,
        user=PGUSER,
        password=PGPASSWORD,
        host=PGHOST,
        port=5432
    )

    # Crear un cursor
    cursor = conn.cursor()

    # Ejecutar una consulta para listar las tablas
    cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")

    # Obtener los resultados
    tables = cursor.fetchall()

    # Imprimir las tablas
    print("Tablas en la base de datos:")
    for table in tables:
        print(table[0])

    # Comprobar si la nueva tabla existe
    if ('new_payments',) in tables:
        print("La tabla 'new_payments' ha sido creada exitosamente.")
    else:
        print("La tabla 'new_payments' no se ha creado.")

    # Cerrar la conexión
    cursor.close()
    conn.close()
else:
    print("No se pudo importar el DataFrame.")

SQL: SELECT * FROM payments

/tmp/ipykernel_4576/2397012419.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, conn)

     customernumber checknumber paymentdate    amount
0               103    HQ336336  2004-10-19   6066.78
1               103    JM555205  2003-06-05  14571.44
2               103    OM314933  2004-12-18   1676.14
3               112    BO864823  2004-12-17  14191.12
4               112     HQ55022  2003-06-06  32641.98
..              ...         ...         ...       ...
254             495    BH167026  2003-12-26  59265.14
255             495    FN155234  2004-05-14   6276.60
256             496    EU531600  2005-05-25  30253.75
257             496    MB342426  2003-07-16  32077.44
258             496     MN89921  2004-12-31  52166.00

[259 rows x 4 columns]
Tablas en la base de datos:
employees
customers
payments
sales
products
datafund_students
new_payments
La tabla 'new_payments' ha sido creada exitosamente.

In [36]:
dfcol.describe()

            edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

In [37]:
dfcol

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

OPERACIONES COLUMNAS

In [15]:
dfcol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      14 non-null     object
 1   edad        14 non-null     int64
 2   sexo        14 non-null     object
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 800.0+ bytes

In [41]:
dfcol['edad'].describe()

count    14.000000
mean     38.214286
std      15.621379
min      18.000000
25%      24.750000
50%      35.000000
75%      49.750000
max      68.000000
Name: edad, dtype: float64

In [43]:
print(dfcol['edad'].count())

14

In [44]:
print(dfcol['edad'].mean())

38.214285714285715

In [45]:
print(dfcol['edad'].std())

15.62137870123737

In [47]:
dfcol.describe()

            edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

In [49]:
dfcol.describe(include='object')

                              nombre sexo
count                             14   14
unique                            14    2
top     José Luis Martínez Izquierdo    H
freq                               1    8

categorias = dfcol.select_dtypes(include='object'): Selecciona todas las columnas en dfcol que tienen el tipo de datos object y las almacena en el DataFrame categorias.

In [55]:
categorias = dfcol.select_dtypes(include='object')
categorias.head()

                         nombre sexo
0  José Luis Martínez Izquierdo    H
1                Rosa Díaz Díaz    M
2         Javier García Sánchez    H
3           Carmen López Pinzón    M
4          Marisa López Collado    M

In [56]:
dfcol

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [16]:
dfcol['imc']=dfcol['peso']/dfcol['altura']**2
dfcol

,nombre,edad,sexo,peso,altura,colesterol,imc
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,26.528510
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,21.718066
2,Javier García Sánchez,24,H,NaN,1.81,191.0,NaN
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,22.491349
4,Marisa López Collado,46,M,51.0,1.58,148.0,20.429418
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,21.799445
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,20.957274
7,Pilar Martín González,22,M,60.0,1.66,NaN,21.773842
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,23.913275
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,21.913806
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,20.957171
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,22.305471
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,27.803285
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,19.470778

In [58]:
dfcol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      14 non-null     object
 1   edad        14 non-null     int64
 2   sexo        14 non-null     object
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
 6   imc         13 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 912.0+ bytes

In [6]:
dfcol['edad']=dfcol['edad'].astype('int32')

FECHA DATE FECHA DATE FECHA DATE FECHA DATE FECHA DATE FECHA DATE FECHA DATE FECHA DATE

In [29]:
dfcol['date']='2024-10-19'
dfcol

,nombre,edad,peso,altura,imc,estado_peso,date
0,José Luis Martínez Izquierdo,18,85.0,1.79,26.528510,sobrepeso,2024-10-19
1,Rosa Díaz Díaz,32,65.0,1.73,21.718066,normal,2024-10-19
2,Javier García Sánchez,24,NaN,1.81,NaN,None,2024-10-19
3,Carmen López Pinzón,35,65.0,1.70,22.491349,normal,2024-10-19
4,Marisa López Collado,46,51.0,1.58,20.429418,normal,2024-10-19
5,Antonio Ruiz Cruz,68,66.0,1.74,21.799445,normal,2024-10-19
6,Antonio Fernández Ocaña,51,62.0,1.72,20.957274,normal,2024-10-19
7,Pilar Martín González,22,60.0,1.66,21.773842,normal,2024-10-19
8,Pedro Gálvez Tenorio,35,90.0,1.94,23.913275,normal,2024-10-19
9,Santiago Reillo Manzano,46,75.0,1.85,21.913806,normal,2024-10-19
10,Macarena Álvarez Luna,53,55.0,1.62,20.957171,normal,2024-10-19
11,José María de la Guía Sanz,58,78.0,1.87,22.305471,normal,2024-10-19
12,Miguel Angel Cuadrado Gutiérrez,27,109.0,1.98,27.803285,sobrepeso,2024-10-19
13,Carolina Rubio Moreno,20,61.0,1.77,19.470778,normal,2024-10-19

In [67]:
dfcol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      14 non-null     object
 1   edad        14 non-null     int32
 2   sexo        14 non-null     object
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
 6   imc         13 non-null     float64
 7   date        14 non-null     object
dtypes: float64(4), int32(1), object(3)
memory usage: 968.0+ bytes

Para agregar una columna de fechas a un DataFrame y convertirla al tipo de datos datetime,
Crear el DataFrame con una columna de fechas en formato de cadena.
Convertir la columna de fechas al tipo de datos datetime.

In [82]:
dfcol['date'] = pd.to_datetime(dfcol['date'], format='%Y/%m/%d')

In [74]:
#print(dfcol['date'].dt)
print(dfcol['date'].dt.year)
#print(dfcol['date'].dt.month)
#print(dfcol['date'].dt.day)

0     2025
1     2025
2     2025
3     2025
4     2025
5     2025
6     2025
7     2025
8     2025
9     2025
10    2025
11    2025
12    2025
13    2025
Name: date, dtype: int64

In [76]:
print(dfcol['date'].dt.to_period('M'))

0     2025-01
1     2025-01
2     2025-01
3     2025-01
4     2025-01
5     2025-01
6     2025-01
7     2025-01
8     2025-01
9     2025-01
10    2025-01
11    2025-01
12    2025-01
13    2025-01
Name: date, dtype: period[M]

#### IMPORTANTE CALCULAR INTERVALOS DE TIEMPO    ------    RESTAR FECHAS

In [83]:
import datetime

ahora = datetime.datetime.now()
print(ahora)

diff_in_days = ahora - dfcol['date']
print(diff_in_days)

2025-01-28 08:11:43.324816
0    101 days 08:11:43.324816
1    101 days 08:11:43.324816
2    101 days 08:11:43.324816
3    101 days 08:11:43.324816
4    101 days 08:11:43.324816
5    101 days 08:11:43.324816
6    101 days 08:11:43.324816
7    101 days 08:11:43.324816
8    101 days 08:11:43.324816
9    101 days 08:11:43.324816
10   101 days 08:11:43.324816
11   101 days 08:11:43.324816
12   101 days 08:11:43.324816
13   101 days 08:11:43.324816
Name: date, dtype: timedelta64[ns]

In [4]:
from math import log

In [5]:
dfcol['altura'].apply(log)

0     0.582216
1     0.548121
2     0.593327
3     0.530628
4     0.457425
5     0.553885
6     0.542324
7     0.506818
8     0.662688
9     0.615186
10    0.482426
11    0.625938
12    0.683097
13    0.570980
Name: altura, dtype: float64

APLICAR FUNCION A UNA COLUMNA PARA CATEGORIZAR EN FUNCION DEL PESO

In [28]:
  def calc_es_sobrepeso(val):
    if  val < 18.5 : return 'bajo'
    elif val >= 18.5  and val <= 24.9: return 'normal'
    elif val >= 25  and val <= 29.9: return 'sobrepeso'
    elif val >= 30: return 'obeso'

dfcol['estado_peso']=dfcol['imc'].apply(calc_es_sobrepeso)

dfcol

,nombre,edad,peso,altura,imc,estado_peso
0,José Luis Martínez Izquierdo,18,85.0,1.79,26.528510,sobrepeso
1,Rosa Díaz Díaz,32,65.0,1.73,21.718066,normal
2,Javier García Sánchez,24,NaN,1.81,NaN,None
3,Carmen López Pinzón,35,65.0,1.70,22.491349,normal
4,Marisa López Collado,46,51.0,1.58,20.429418,normal
5,Antonio Ruiz Cruz,68,66.0,1.74,21.799445,normal
6,Antonio Fernández Ocaña,51,62.0,1.72,20.957274,normal
7,Pilar Martín González,22,60.0,1.66,21.773842,normal
8,Pedro Gálvez Tenorio,35,90.0,1.94,23.913275,normal
9,Santiago Reillo Manzano,46,75.0,1.85,21.913806,normal
10,Macarena Álvarez Luna,53,55.0,1.62,20.957171,normal
11,José María de la Guía Sanz,58,78.0,1.87,22.305471,normal
12,Miguel Angel Cuadrado Gutiérrez,27,109.0,1.98,27.803285,sobrepeso
13,Carolina Rubio Moreno,20,61.0,1.77,19.470778,normal

EXTRAER UNA COLUMNA DEL DATAFRAME Y ALMACENARLO EN UNA VARIABLE

En un DataFrame de pandas, tanto pop como drop se utilizan para eliminar datos, pero tienen diferencias importantes en su funcionamiento y uso. Aquí está una explicación de cada uno:

pop
Función: Elimina una columna del DataFrame y devuelve esa columna como una Serie.
Modifica el DataFrame original: Sí, pop modifica el DataFrame original eliminando la columna especificada.
Uso: Se utiliza principalmente cuando necesitas eliminar una columna y al mismo tiempo trabajar con los datos de esa columna.

In [15]:
sexo = dfcol.pop('sexo')
print(sexo)

print(dfcol)

0     H
1     M
2     H
3     M
4     M
5     H
6     H
7     M
8     H
9     H
10    M
11    H
12    H
13    M
Name: sexo, dtype: object
                             nombre  edad   peso  altura        imc  \
0      José Luis Martínez Izquierdo    18   85.0    1.79  26.528510
1                    Rosa Díaz Díaz    32   65.0    1.73  21.718066
2             Javier García Sánchez    24    NaN    1.81        NaN
3               Carmen López Pinzón    35   65.0    1.70  22.491349
4              Marisa López Collado    46   51.0    1.58  20.429418
5                 Antonio Ruiz Cruz    68   66.0    1.74  21.799445
6           Antonio Fernández Ocaña    51   62.0    1.72  20.957274
7             Pilar Martín González    22   60.0    1.66  21.773842
8              Pedro Gálvez Tenorio    35   90.0    1.94  23.913275
9           Santiago Reillo Manzano    46   75.0    1.85  21.913806
10            Macarena Álvarez Luna    53   55.0    1.62  20.957171
11       José María de la Guía Sanz    58   78.0    1.87  22.305471
12  Miguel Angel Cuadrado Gutiérrez    27  109.0    1.98  27.803285
13            Carolina Rubio Moreno    20   61.0    1.77  19.470778

   estado_peso
0    sobrepeso
1       normal
2         None
3       normal
4       normal
5       normal
6       normal
7       normal
8       normal
9       normal
10      normal
11      normal
12   sobrepeso
13      normal

OPERACIONES DE FILAS.   AÑADIR NUEVAS FILAS. HAY QUE UTILIZAR OTRO DATAFRAME Y USAR CONCAT.  NO PERMITE AÑADIR LISTA A DATAFRAME

In [16]:
dfcol

,nombre,edad,peso,altura,imc,estado_peso
0,José Luis Martínez Izquierdo,18,85.0,1.79,26.528510,sobrepeso
1,Rosa Díaz Díaz,32,65.0,1.73,21.718066,normal
2,Javier García Sánchez,24,NaN,1.81,NaN,None
3,Carmen López Pinzón,35,65.0,1.70,22.491349,normal
4,Marisa López Collado,46,51.0,1.58,20.429418,normal
5,Antonio Ruiz Cruz,68,66.0,1.74,21.799445,normal
6,Antonio Fernández Ocaña,51,62.0,1.72,20.957274,normal
7,Pilar Martín González,22,60.0,1.66,21.773842,normal
8,Pedro Gálvez Tenorio,35,90.0,1.94,23.913275,normal
9,Santiago Reillo Manzano,46,75.0,1.85,21.913806,normal
10,Macarena Álvarez Luna,53,55.0,1.62,20.957171,normal
11,José María de la Guía Sanz,58,78.0,1.87,22.305471,normal
12,Miguel Angel Cuadrado Gutiérrez,27,109.0,1.98,27.803285,sobrepeso
13,Carolina Rubio Moreno,20,61.0,1.77,19.470778,normal

In [17]:
nfila =dfcol.iloc[-1]
nfila

nombre        Carolina Rubio Moreno
edad                             20
sexo                              M
peso                           61.0
altura                         1.77
colesterol                    194.0
imc                       19.470778
Name: 13, dtype: object

In [19]:
dfd = pd.DataFrame([nfila])
dfd

                   nombre  edad sexo  peso  altura  colesterol        imc
13  Carolina Rubio Moreno    20    M  61.0    1.77       194.0  19.470778

In [20]:
pd.concat((dfcol, dfd), ignore_index=True)

,nombre,edad,sexo,peso,altura,colesterol,imc
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,26.528510
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,21.718066
2,Javier García Sánchez,24,H,NaN,1.81,191.0,NaN
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,22.491349
4,Marisa López Collado,46,M,51.0,1.58,148.0,20.429418
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,21.799445
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,20.957274
7,Pilar Martín González,22,M,60.0,1.66,NaN,21.773842
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,23.913275
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,21.913806
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,20.957171
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,22.305471
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,27.803285
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,19.470778
14,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,19.470778

ELIMINAR UNA FILA DE UN DATAFRAME.    DROP


En un DataFrame de pandas, tanto pop como drop se utilizan para eliminar datos, pero tienen diferencias importantes en su funcionamiento y uso. Aquí está una explicación de cada uno:

pop
Función: Elimina una columna del DataFrame y devuelve esa columna como una Serie.
Modifica el DataFrame original: Sí, pop modifica el DataFrame original eliminando la columna especificada.
Uso: Se utiliza principalmente cuando necesitas eliminar una columna y al mismo tiempo trabajar con los datos de esa columna.
Ejemplo:
Salida:

drop
Función: Elimina filas o columnas del DataFrame.
Modifica el DataFrame original: No, a menos que se utilice el parámetro inplace=True. Por defecto, drop devuelve un nuevo DataFrame con las filas o columnas eliminadas.
Uso: Se utiliza cuando necesitas eliminar filas o columnas sin necesariamente trabajar con los datos eliminados.

In [25]:
dfcol.drop(index=[1,3])

,nombre,edad,peso,altura,imc,estado_peso
0,José Luis Martínez Izquierdo,18,85.0,1.79,26.528510,sobrepeso
2,Javier García Sánchez,24,NaN,1.81,NaN,None
4,Marisa López Collado,46,51.0,1.58,20.429418,normal
5,Antonio Ruiz Cruz,68,66.0,1.74,21.799445,normal
6,Antonio Fernández Ocaña,51,62.0,1.72,20.957274,normal
7,Pilar Martín González,22,60.0,1.66,21.773842,normal
8,Pedro Gálvez Tenorio,35,90.0,1.94,23.913275,normal
9,Santiago Reillo Manzano,46,75.0,1.85,21.913806,normal
10,Macarena Álvarez Luna,53,55.0,1.62,20.957171,normal
11,José María de la Guía Sanz,58,78.0,1.87,22.305471,normal
12,Miguel Angel Cuadrado Gutiérrez,27,109.0,1.98,27.803285,sobrepeso
13,Carolina Rubio Moreno,20,61.0,1.77,19.470778,normal

ELIMINAR LAS FILAS QUE TIENEN NAN

In [26]:
dfcol.dropna()

,nombre,edad,peso,altura,imc,estado_peso
0,José Luis Martínez Izquierdo,18,85.0,1.79,26.528510,sobrepeso
1,Rosa Díaz Díaz,32,65.0,1.73,21.718066,normal
3,Carmen López Pinzón,35,65.0,1.70,22.491349,normal
4,Marisa López Collado,46,51.0,1.58,20.429418,normal
5,Antonio Ruiz Cruz,68,66.0,1.74,21.799445,normal
6,Antonio Fernández Ocaña,51,62.0,1.72,20.957274,normal
7,Pilar Martín González,22,60.0,1.66,21.773842,normal
8,Pedro Gálvez Tenorio,35,90.0,1.94,23.913275,normal
9,Santiago Reillo Manzano,46,75.0,1.85,21.913806,normal
10,Macarena Álvarez Luna,53,55.0,1.62,20.957171,normal
11,José María de la Guía Sanz,58,78.0,1.87,22.305471,normal
12,Miguel Angel Cuadrado Gutiérrez,27,109.0,1.98,27.803285,sobrepeso
13,Carolina Rubio Moreno,20,61.0,1.77,19.470778,normal

REMPLAZAR VALORES

In [32]:
dfcol.replace({'sexo':{'H':'Hombre','M':'Mujer'}})

                             nombre  edad    sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18  Hombre   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32   Mujer   65.0    1.73       232.0
2             Javier García Sánchez    24  Hombre    NaN    1.81       191.0
3               Carmen López Pinzón    35   Mujer   65.0    1.70       200.0
4              Marisa López Collado    46   Mujer   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68  Hombre   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51  Hombre   62.0    1.72       276.0
7             Pilar Martín González    22   Mujer   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35  Hombre   90.0    1.94       241.0
9           Santiago Reillo Manzano    46  Hombre   75.0    1.85       280.0
10            Macarena Álvarez Luna    53   Mujer   55.0    1.62       262.0
11       José María de la Guía Sanz    58  Hombre   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27  Hombre  109.0    1.98       210.0
13            Carolina Rubio Moreno    20   Mujer   61.0    1.77       194.0

ORDENAR

In [18]:
dfcol.sort_values(['peso','altura'], ascending=[True, False])

                             nombre  edad sexo   peso  altura  colesterol
4              Marisa López Collado    46    M   51.0    1.58       148.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0

AGRUPAMIENTOS

El método groupby en un DataFrame de pandas se utiliza para agrupar los datos según una o más columnas. El atributo groups de un objeto GroupBy devuelve un diccionario donde las claves son los valores únicos de la columna utilizada para agrupar y los valores son los índices de las filas que pertenecen a cada grupo.

In [20]:
dfcol.groupby('sexo').groups

{'H': [0, 2, 5, 6, 8, 9, 11, 12], 'M': [1, 3, 4, 7, 10, 13]}

Para utilizar el método get_group de un objeto GroupBy en un DataFrame de pandas, primero debes asegurarte de que el valor que estás buscando existe en la columna por la que estás agrupando. En tu ejemplo, parece que estás buscando el grupo con sexo igual a 'H', pero en los datos proporcionados solo existen los valores 'F' y 'M'.

In [21]:
print(dfcol.groupby('sexo').get_group('H'))

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0

In [27]:
print(dfcol.groupby(['sexo','peso']).groups)
print(dfcol.groupby(['sexo','peso']).first())

{('H', 85.0): [0], ('H', nan): [2], ('H', 62.0): [6], ('H', 66.0): [5], ('H', 75.0): [9], ('H', 78.0): [11], ('H', 90.0): [8], ('H', 109.0): [12], ('M', 51.0): [4], ('M', 55.0): [10], ('M', 60.0): [7], ('M', 61.0): [13], ('M', 65.0): [1, 3]}
                                     nombre  edad  altura  colesterol
sexo peso
H    62.0           Antonio Fernández Ocaña    51    1.72       276.0
     66.0                 Antonio Ruiz Cruz    68    1.74       249.0
     75.0           Santiago Reillo Manzano    46    1.85       280.0
     78.0        José María de la Guía Sanz    58    1.87       198.0
     85.0      José Luis Martínez Izquierdo    18    1.79       182.0
     90.0              Pedro Gálvez Tenorio    35    1.94       241.0
     109.0  Miguel Angel Cuadrado Gutiérrez    27    1.98       210.0
M    51.0              Marisa López Collado    46    1.58       148.0
     55.0             Macarena Álvarez Luna    53    1.62       262.0
     60.0             Pilar Martín González    22    1.66         NaN
     61.0             Carolina Rubio Moreno    20    1.77       194.0
     65.0                    Rosa Díaz Díaz    32    1.73       232.0

In [32]:
import numpy as np
dfcol.aggregate([np.sum])
dfcol.aggregate([np.sum,'min','max'])

,nombre,edad,sexo,peso,altura,colesterol
sum,José Luis Martínez IzquierdoRosa Díaz DíazJavi...,535,HMHMMHHMHHMHHM,922.0,24.76,2863.0
min,Antonio Fernández Ocaña,18,H,51.0,1.58,148.0
max,Santiago Reillo Manzano,68,M,109.0,1.98,280.0

AGREGACION sobre los grupos previamente extraidos    A UN GROUPBY LE AÑADO LA AGREGACION

In [30]:
print(dfcol.groupby('sexo').first())

                            nombre  edad  peso  altura  colesterol
sexo
H     José Luis Martínez Izquierdo    18  85.0    1.79       182.0
M                   Rosa Díaz Díaz    32  65.0    1.73       232.0

In [31]:
dfcol.groupby('sexo').agg(np.sum)

/tmp/ipykernel_3548/1138427538.py:1: FutureWarning: The operation <function sum at 0x7f39203e4c10> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  dfcol.groupby('sexo').agg(np.sum)

      edad   peso  altura  colesterol
sexo
H      327  565.0   14.70      1827.0
M      208  357.0   10.06      1036.0

PODEMOS ESPECIFICAR SOBRE QUE COLUMNAS QUEREMOS AGREGAR

dfcol.groupby('sexo') agrupa el DataFrame por la columna sexo.
.agg({'edad': np.sum, 'colesterol': np.mean}) aplica la función np.sum a la columna edad y la función np.mean a la columna colesterol para cada grupo.
El resultado es un nuevo DataFrame que muestra la suma de las edades y el promedio de los niveles de colesterol para cada grupo de sexo.

In [33]:
dfcol.groupby('sexo').agg({'edad':np.sum, 'colesterol':np.mean})

      edad  colesterol
sexo
H      327     228.375
M      208     207.200

pd.cut(x=dfcol['edad'], bins=[1, 20, 40, 60, 80, 100]) clasifica las edades en los intervalos [1, 20], (20, 40], (40, 60], (60, 80], y (80, 100].
La nueva columna rangos_edad contiene los intervalos correspondientes a cada edad en el DataFrame.

In [47]:
dfcol['rangos_edad']= pd.cut(x=dfcol['edad'],bins=[1,20,40,60,80,100])
dfcol

,nombre,edad,sexo,peso,altura,colesterol,rangos_edad
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,"(1, 20]"
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,"(20, 40]"
2,Javier García Sánchez,24,H,NaN,1.81,191.0,"(20, 40]"
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,"(20, 40]"
4,Marisa López Collado,46,M,51.0,1.58,148.0,"(40, 60]"
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,"(60, 80]"
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,"(40, 60]"
7,Pilar Martín González,22,M,60.0,1.66,NaN,"(20, 40]"
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,"(20, 40]"
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,"(40, 60]"
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,"(40, 60]"
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,"(40, 60]"
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,"(20, 40]"
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,"(1, 20]"

CONCATENACION DE DATAFRAMES

In [21]:
df1 = pd.DataFrame({"Nombre": ["Carmen", "Luis"],
                      "Sexo": ["Mujer", "Hombre"], "Edad": [22, 18]}).set_index("Nombre")
df2 = pd.DataFrame({"Nombre": ["María", "Pedro"],
                      "Sexo": ["Mujer", "Hombre"], "Edad": [25, 30]}).set_index("Nombre")

In [22]:
df =pd.concat([df1,df2], axis=0)
df

          Sexo  Edad
Nombre
Carmen   Mujer    22
Luis    Hombre    18
María    Mujer    25
Pedro   Hombre    30

In [26]:
df1 = pd.DataFrame({"Nombre": ["Carmen", "Luis", "María"],
                    "Sexo": ["Mujer", "Hombre", "Mujer"]}).set_index("Nombre")
df2 = pd.DataFrame({"Nombre": ["Carmen", "Luis", "María"],
                    "Edad": [22, 18, 25]}).set_index("Nombre")
df1

          Sexo
Nombre
Carmen   Mujer
Luis    Hombre
María    Mujer

El método pd.merge se utiliza para combinar dos DataFrames en función de una o más claves. En tu ejemplo, deseas realizar una combinación interna (inner join) de los DataFrames df1 y df2 utilizando la columna Nombre como clave.

In [24]:
df =pd.merge(df1, df2, how="inner", on="Nombre")
df

          Sexo  Edad
Nombre
Carmen   Mujer    22
Luis    Hombre    18
María    Mujer    25

In [27]:
dfcol

,nombre,edad,sexo,peso,altura,colesterol,imc
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,26.528510
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,21.718066
2,Javier García Sánchez,24,H,NaN,1.81,191.0,NaN
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,22.491349
4,Marisa López Collado,46,M,51.0,1.58,148.0,20.429418
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,21.799445
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,20.957274
7,Pilar Martín González,22,M,60.0,1.66,NaN,21.773842
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,23.913275
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,21.913806
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,20.957171
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,22.305471
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,27.803285
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,19.470778

El método pd.crosstab se utiliza para crear una tabla de contingencia que muestra la frecuencia de las combinaciones de valores en dos o más columnas. En tu ejemplo, deseas crear una tabla de contingencia que muestre el promedio de los valores de la columna colesterol para cada combinación de sexo y peso.

In [50]:
ct_means =pd.crosstab(dfcol['sexo'], dfcol['peso'],values=dfcol['colesterol'], aggfunc='mean',margins=True)
ct_means

peso,51.0,55.0,61.0,62.0,65.0,66.0,75.0,78.0,85.0,90.0,109.0,All
sexo,,,,,,,,,,,,
H,NaN,NaN,NaN,276.0,NaN,249.0,280.0,198.0,182.0,241.0,210.0,233.714286
M,148.0,262.0,194.0,NaN,216.0,NaN,NaN,NaN,NaN,NaN,NaN,207.200000
All,148.0,262.0,194.0,276.0,216.0,249.0,280.0,198.0,182.0,241.0,210.0,222.666667